apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokeapi
  template:
    metadata:
      labels:
        app: pokeapi
    spec:
      containers:
        - image: pokeapi:0.1
          name: pokeapi
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: START
              valueFrom:
                configMapKeyRef:
                  name: api-cm
                  key: START
            - name: STOP
              valueFrom:
                configMapKeyRef:
                  name: api-cm
                  key: START
          ports:
            - containerPort: 3000
